#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
#### FUNCTION: POOL RESULTS ACROSS MICE DATA FRAMES ####
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#

#+++
# by Lana Kern
#+++
# This function aggregates the treatment effect estimates across the MICE 
# data frames.
#+++
# INPUT:
# -> "dml_result": list result from applying "func_dml"
# -> "N": total number of observations
# -> "mice_num": total number of data frames generated by MICE
#+++
# OUTPUT:
# -> "estimates": aggregated treatment effects, se, etc. across the MICE data sets
# -> "error": mean error metrics across the MICE data sets
#+++

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#

func_dml_pool_mice <- function(dml_result, N, mice_num) {
  
  # store final estimates of each mice data set in one data frame
  dml_final <- data.frame()
  if (is.null(dml_result[[1]]$final)) {
    for (mice_data_sel in 1:mice_num) {
      dml_final <- rbind(
        dml_final,
        dml_result[[mice_data_sel]] %>% mutate(MICE = mice_data_sel) %>%
          dplyr::select(MICE, everything())
      )
    }
  } else {
    for (mice_data_sel in 1:mice_num) {
      dml_final <- rbind(
        dml_final,
        dml_result[[mice_data_sel]]$final %>% mutate(MICE = mice_data_sel) %>%
          dplyr::select(MICE, everything())
      )
    }
  }
  
  # do the same for error metrics
  if (!is.null(dml_result[[1]]$error)) {
    dml_error <- data.frame()
    for (mice_data_sel in 1:mice_num) {
      dml_error <- rbind(
        dml_error,
        dml_result[[mice_data_sel]]$error %>% mutate(MICE = mice_data_sel) %>%
          dplyr::select(MICE, everything())
      )
    }
  }
  
  # do the same for the predictors
  if (!is.null(dml_result[[1]]$predictors)) {
    dml_pred <- data.frame()
    for (mice_data_sel in 1:mice_num) {
      dml_pred <- rbind(
        dml_pred,
        dml_result[[mice_data_sel]]$predictors %>% mutate(MICE = mice_data_sel) %>%
          dplyr::select(MICE, everything())
      )
    }
  }
  
  # aggregate results across MICE data sets: simply take mean of
  # estimates, se, p-value and t-value (for p-value and t-value new calculation
  # yields same result). However, the confidence interval is calculated again.
  dml_final_estimation <-
    dml_final %>%
    dplyr::select(Treatment, Type, starts_with("theta"), starts_with("se"), matches(".*value")) %>%
    group_by(Treatment, Type) %>%
    summarize(
      theta_mean = mean(theta_mean), theta_median = mean(theta_median),
      se_mean = mean(se_mean), se_median = mean(se_median),
      tvalue_mean = mean(tvalue_mean), tvalue_median = mean(tvalue_median),
      pvalue_mean = mean(pvalue_mean), pvalue_median = mean(pvalue_median)
    ) %>%
    mutate(
      # confidence interval
      CI_lower_mean_95 = theta_mean - qt(0.95, df = N - 1)^-1 * (1 - 0.95 / 2) * se_mean / sqrt(N),
      CI_upper_mean_95 = theta_mean + qt(0.95, df = N - 1)^-1 * (1 - 0.95 / 2) * se_mean / sqrt(N),
      CI_lower_median_95 = theta_median - qt(0.95, df = N - 1)^-1 * (1 - 0.95 / 2) * se_median / sqrt(N),
      CI_upper_median_95 = theta_median + qt(0.95, df = N - 1)^-1 * (1 - 0.95 / 2) * se_median / sqrt(N)
    )
  
  # number of predictors
  if (!is.null(dml_result[[1]]$predictors)) {
    if (any(str_detect(colnames(dml_pred), "m2"))) {
      # multivalued treatment setting
      dml_final_estimation <- dml_final_estimation %>%
        mutate(
          num_predictors_m1 = mean(dml_pred$num_pred_m1), num_predictors_m2 = mean(dml_pred$num_pred_m2),
          num_predictors_m3 = mean(dml_pred$num_pred_m3), 
          num_predictors_g1 = mean(dml_pred$num_pred_g1), num_predictors_g2 = mean(dml_pred$num_pred_g2), 
          num_predictors_g3 = mean(dml_pred$num_pred_g3)
        )
    } else {
      # binary treatment setting
      dml_final_estimation <- dml_final_estimation %>%
        mutate(
          num_predictors_m = mean(dml_pred$num_pred_m), num_predictors_g0 = mean(dml_pred$num_pred_g0), 
          num_predictors_g1 = mean(dml_pred$num_pred_g1)
        )
    }
  } else {
    dml_final_estimation <- dml_final_estimation
  }
  
  
  # aggregate errors
  if (exists("dml_error")) {
    
    dml_final_error <- dml_error %>% 
      dplyr::select(-c(MICE, Repetition, Fold)) %>% 
      summarise_if(is.numeric, mean) 

    # return results
    return(list("estimates" = dml_final_estimation, "errors" = dml_final_error))
  } else {
    return(dml_final_estimation)
  }
}